export const FETCH_ACCOMODATION_LIST_REQUEST =
  "FETCH_ACCOMODATION_LIST_REQUEST";
export const FETCH_ACCOMODATION_LIST_SUCCESS =
  "FETCH_ACCOMODATION_LIST_SUCCESS";
export const FETCH_ACCOMODATION_LIST_FAILURE =
  "FETCH_ACCOMODATION_LIST_FAILURE";
